export const NAVIGATION_LINKS = [
  { label: "Shop All", href: "/collections" },
  { label: "Workspace", href: "/collections?category=workspace" },
  { label: "Productivity", href: "/collections?category=productivity" },
  { label: "Creator Gear", href: "/collections?category=creator-gear" },
  { label: "Lifestyle", href: "/collections?category=lifestyle" },
  { label: "About", href: "/about" },
];

export const ANNOUNCEMENT_MESSAGES = [
  "New workspace collection — monitor arms, docks & lighting just dropped",
  "Creator Gear: Stream Decks, Microphones & Studio Setups now available",
  "Digital downloads now live — Notion templates, icon packs & more",
  "Free shipping on orders over $100 · Easy 30-day returns",
];

export const CATEGORIES = [
  {
    name: "Mechanical Keyboards",
    slug: "keyboards",
    image: "https://images.unsplash.com/photo-1618384852429-e259b09e6904?w=800&q=80",
    description: "Premium tactile typing",
  },
  {
    name: "Workspace Tech",
    slug: "workspace",
    image: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=800&q=80",
    description: "Monitors, docks & lighting",
  },
  {
    name: "Creator Gear",
    slug: "creator-gear",
    image: "https://images.unsplash.com/photo-1598550874175-4d0ef436c909?w=800&q=80",
    description: "Mics, cams & stream setups",
  },
  {
    name: "Productivity",
    slug: "productivity",
    image: "https://images.unsplash.com/photo-1531346878377-a5be20888e57?w=800&q=80",
    description: "Deep work tools & journals",
  },
  {
    name: "Lifestyle",
    slug: "lifestyle",
    image: "https://images.unsplash.com/photo-1608181831718-c9fdc9a86f14?w=800&q=80",
    description: "Candles, ceramics & ambience",
  },
  {
    name: "Audio",
    slug: "audio",
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80",
    description: "Headphones & speakers",
  },
  {
    name: "Ergonomics",
    slug: "ergonomics",
    image: "https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=800&q=80",
    description: "Desks, chairs & mats",
  },
  {
    name: "Digital",
    slug: "digital",
    image: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&q=80",
    description: "Templates, packs & guides",
  },
];

export interface Product {
  id: string;
  slug: string;
  name: string;
  brand: string;
  price: number;
  originalPrice?: number;
  category: string;
  rating: number;
  reviewCount: number;
  image: string;
  hoverImage: string;
  isNew?: boolean;
  isBestseller?: boolean;
  isDigital?: boolean;
  description: string;
  features: string[];
}

export const PRODUCTS: Product[] = [
  // ─── Keyboards ────────────────────────────────────────────────────────────
  {
    id: "1",
    slug: "nuphy-air75-v2",
    name: "NuPhy Air75 V2",
    brand: "NuPhy",
    price: 149,
    category: "keyboards",
    rating: 4.8,
    reviewCount: 284,
    image: "https://images.unsplash.com/photo-1618384852429-e259b09e6904?w=800&q=80",
    hoverImage: "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=800&q=80",
    isNew: true,
    description: "Ultra-slim 75% wireless mechanical keyboard with hot-swappable switches and premium aluminum frame.",
    features: ["Hot-swappable switches", "Wireless & wired", "Aluminum frame", "RGB backlit"],
  },
  {
    id: "2",
    slug: "yunzii-al71",
    name: "Yunzii AL71",
    brand: "Yunzii",
    price: 89,
    category: "keyboards",
    rating: 4.6,
    reviewCount: 147,
    image: "https://images.unsplash.com/photo-1587829741161-75e44d972ed6?w=800&q=80",
    hoverImage: "https://images.unsplash.com/photo-1599599810769-bcde5a160d32?w=800&q=80",
    description: "Compact 71-key wireless keyboard with a clean aesthetic and satisfying tactile typing experience.",
    features: ["Bluetooth 5.0", "Hot-swappable", "Gasket mount", "POM plate"],
  },
  {
    id: "3",
    slug: "keychron-k3-pro",
    name: "Keychron K3 Pro",
    brand: "Keychron",
    price: 119,
    category: "keyboards",
    rating: 4.7,
    reviewCount: 512,
    image: "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=800&q=80",
    hoverImage: "https://images.unsplash.com/photo-1618384852429-e259b09e6904?w=800&q=80",
    isBestseller: true,
    description: "Ultra-slim 75% layout with low-profile switches for a laptop-like feel with mechanical key travel.",
    features: ["Low-profile switches", "Multi-device", "Mac/Windows", "RGB"],
  },
  {
    id: "4",
    slug: "lofree-flow",
    name: "Lofree Flow",
    brand: "Lofree",
    price: 199,
    originalPrice: 249,
    category: "keyboards",
    rating: 4.9,
    reviewCount: 89,
    image: "https://images.unsplash.com/photo-1593642632632-9c8dfccbcbb7?w=800&q=80",
    hoverImage: "https://images.unsplash.com/photo-1587829741161-75e44d972ed6?w=800&q=80",
    isNew: true,
    description: "Premium low-profile keyboard with ghost switches and minimalist, elegant design.",
    features: ["Ghost switches", "Wireless", "CNC aluminum", "Foam dampening"],
  },
  {
    id: "5",
    slug: "varmilo-va87m",
    name: "Varmilo VA87M",
    brand: "Varmilo",
    price: 179,
    category: "keyboards",
    rating: 4.7,
    reviewCount: 203,
    image: "https://images.unsplash.com/photo-1563191911-e65a8f3e5e9e?w=800&q=80",
    hoverImage: "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=800&q=80",
    description: "Premium TKL keyboard with custom dye-sub PBT keycaps and smooth, linear switches.",
    features: ["Custom keycaps", "TKL layout", "Multimedia keys", "N-key rollover"],
  },
  {
    id: "6",
    slug: "hhkb-professional",
    name: "HHKB Professional",
    brand: "PFU",
    price: 299,
    category: "keyboards",
    rating: 4.9,
    reviewCount: 156,
    image: "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=800&q=80",
    hoverImage: "https://images.unsplash.com/photo-1618384852429-e259b09e6904?w=800&q=80",
    description: "The legendary Happy Hacking Keyboard with electrostatic capacitive switches for the ultimate typing feel.",
    features: ["EC switches", "Topre mechanism", "60% layout", "Bluetooth"],
  },

  // ─── Accessories (legacy) ─────────────────────────────────────────────────
  {
    id: "7",
    slug: "grovemade-desk-mat",
    name: "Grovemade Desk Mat",
    brand: "Grovemade",
    price: 95,
    category: "accessories",
    rating: 4.8,
    reviewCount: 341,
    image: "https://images.unsplash.com/photo-1593642632632-9c8dfccbcbb7?w=800&q=80",
    hoverImage: "https://images.unsplash.com/photo-1587829741161-75e44d972ed6?w=800&q=80",
    isBestseller: true,
    description: "Premium full-grain leather desk mat that protects your desk and elevates your workspace aesthetic.",
    features: ["Full-grain leather", "Non-slip base", "Multiple colors", "Aged beautifully"],
  },
  {
    id: "8",
    slug: "twelve-south-hirise",
    name: "Twelve South HiRise",
    brand: "Twelve South",
    price: 79,
    category: "accessories",
    rating: 4.6,
    reviewCount: 189,
    image: "https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=800&q=80",
    hoverImage: "https://images.unsplash.com/photo-1593642632632-9c8dfccbcbb7?w=800&q=80",
    description: "Adjustable laptop stand that raises your screen to eye level for better ergonomics and posture.",
    features: ["Adjustable height", "Premium finish", "Cable management", "Universal fit"],
  },
  {
    id: "9",
    slug: "peak-design-everyday",
    name: "Peak Design Everyday Case",
    brand: "Peak Design",
    price: 69,
    category: "accessories",
    rating: 4.7,
    reviewCount: 428,
    image: "https://images.unsplash.com/photo-1610701596007-11502861dcfa?w=800&q=80",
    hoverImage: "https://images.unsplash.com/photo-1593642632632-9c8dfccbcbb7?w=800&q=80",
    description: "Versatile phone stand and case system with MagSafe compatibility and minimalist design.",
    features: ["MagSafe", "Multiple positions", "Slim profile", "Drop protection"],
  },

  // ─── Audio ────────────────────────────────────────────────────────────────
  {
    id: "10",
    slug: "sony-wh-1000xm5",
    name: "Sony WH-1000XM5",
    brand: "Sony",
    price: 349,
    originalPrice: 399,
    category: "audio",
    rating: 4.9,
    reviewCount: 892,
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80",
    hoverImage: "https://images.unsplash.com/photo-1577174881658-0f30ed549adc?w=800&q=80",
    isBestseller: true,
    description: "Industry-leading noise canceling headphones with exceptional sound quality for deep work sessions.",
    features: ["ANC", "30hr battery", "Multipoint connect", "Speak-to-chat"],
  },

  // ─── Workspace Tech ───────────────────────────────────────────────────────
  {
    id: "11",
    slug: "ergotron-lx-monitor-arm",
    name: "Ergotron LX Monitor Arm",
    brand: "Ergotron",
    price: 179,
    category: "workspace",
    rating: 4.8,
    reviewCount: 1247,
    image: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=800&q=80",
    hoverImage: "https://images.unsplash.com/photo-1593640408182-31c228b03e4f?w=800&q=80",
    isBestseller: true,
    description: "Premium articulating monitor arm with smooth repositioning and cable management for a clean, floating desk setup.",
    features: ["360° rotation", "Easy height adjust", "Integrated cable mgmt", "VESA compatible"],
  },
  {
    id: "12",
    slug: "benq-screenbar-halo",
    name: "BenQ ScreenBar Halo",
    brand: "BenQ",
    price: 219,
    category: "workspace",
    rating: 4.7,
    reviewCount: 632,
    image: "https://images.unsplash.com/photo-1513506003901-1e6a35f83338?w=800&q=80",
    hoverImage: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=800&q=80",
    isNew: true,
    description: "Asymmetric optical design reduces eye strain with front-facing task light and back-glow ambient halo.",
    features: ["Auto-dimming", "No screen glare", "Ambient back glow", "USB-C powered"],
  },
  {
    id: "13",
    slug: "caldigit-ts4-thunderbolt-dock",
    name: "CalDigit TS4 Dock",
    brand: "CalDigit",
    price: 349,
    category: "workspace",
    rating: 4.8,
    reviewCount: 489,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    hoverImage: "https://images.unsplash.com/photo-1593640408182-31c228b03e4f?w=800&q=80",
    description: "Thunderbolt 4 dock with 18 ports including dual 4K display support and 98W host charging.",
    features: ["18 ports", "98W charging", "Dual 4K support", "Thunderbolt 4"],
  },
  {
    id: "14",
    slug: "elgato-key-light",
    name: "Elgato Key Light",
    brand: "Elgato",
    price: 199,
    category: "workspace",
    rating: 4.7,
    reviewCount: 3218,
    image: "https://images.unsplash.com/photo-1598550874175-4d0ef436c909?w=800&q=80",
    hoverImage: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=800&q=80",
    isNew: true,
    description: "Professional-grade desk light with app-controlled color temperature and brightness for perfect video calls.",
    features: ["2500–6500K range", "App control", "Low heat LED", "Desk mountable"],
  },
  {
    id: "15",
    slug: "anker-usb-c-hub-7in1",
    name: "Anker USB-C Hub 7-in-1",
    brand: "Anker",
    price: 55,
    category: "workspace",
    rating: 4.6,
    reviewCount: 2104,
    image: "https://images.unsplash.com/photo-1593640408182-31c228b03e4f?w=800&q=80",
    hoverImage: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    description: "Compact 7-in-1 USB-C hub adding HDMI 4K, USB-A, SD card slots and 100W pass-through charging.",
    features: ["4K HDMI", "100W PD", "SD/microSD", "USB-A 3.0 x2"],
  },

  // ─── Productivity ─────────────────────────────────────────────────────────
  {
    id: "16",
    slug: "field-notes-notebook-pack",
    name: "Field Notes 3-Pack",
    brand: "Field Notes",
    price: 13,
    category: "productivity",
    rating: 4.7,
    reviewCount: 892,
    image: "https://images.unsplash.com/photo-1531346878377-a5be20888e57?w=800&q=80",
    hoverImage: "https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800&q=80",
    description: "Pocket-sized memo books with a sturdy cover and graph-ruled paper — a daily carry staple.",
    features: ["48 pages each", "Graph ruled", "Lay-flat binding", "Made in USA"],
  },
  {
    id: "17",
    slug: "remarkable-2-tablet",
    name: "reMarkable 2",
    brand: "reMarkable",
    price: 449,
    category: "productivity",
    rating: 4.6,
    reviewCount: 1103,
    image: "https://images.unsplash.com/photo-1544725176-7c40e5a71c5e?w=800&q=80",
    hoverImage: "https://images.unsplash.com/photo-1531346878377-a5be20888e57?w=800&q=80",
    isNew: true,
    description: "The world's thinnest digital notebook — paper-like E Ink writing that replaces notebooks and documents.",
    features: ["E Ink display", "Paper-like feel", "Cloud sync", "2-week battery"],
  },
  {
    id: "18",
    slug: "lamy-2000-fountain-pen",
    name: "Lamy 2000 Fountain Pen",
    brand: "Lamy",
    price: 165,
    category: "productivity",
    rating: 4.9,
    reviewCount: 347,
    image: "https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800&q=80",
    hoverImage: "https://images.unsplash.com/photo-1531346878377-a5be20888e57?w=800&q=80",
    isBestseller: true,
    description: "A Bauhaus icon since 1966. Made from Makrolon with a 14-carat gold nib that writes like a dream.",
    features: ["14k gold nib", "Makrolon body", "Piston mechanism", "Timeless design"],
  },
  {
    id: "19",
    slug: "time-timer-original",
    name: "Time Timer Original",
    brand: "Time Timer",
    price: 35,
    category: "productivity",
    rating: 4.5,
    reviewCount: 568,
    image: "https://images.unsplash.com/photo-1501139083538-0139583c060f?w=800&q=80",
    hoverImage: "https://images.unsplash.com/photo-1531346878377-a5be20888e57?w=800&q=80",
    description: "Visual timer that makes time tangible — perfect for Pomodoro sessions, focus blocks, and time boxing.",
    features: ["Visual countdown", "Silent mode", "60-min range", "Battery powered"],
  },
  {
    id: "20",
    slug: "moleskine-pro-planner",
    name: "Moleskine Pro Planner",
    brand: "Moleskine",
    price: 42,
    category: "productivity",
    rating: 4.6,
    reviewCount: 723,
    image: "https://images.unsplash.com/photo-1506784983877-45594efa4cbe?w=800&q=80",
    hoverImage: "https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800&q=80",
    description: "Weekly horizontal planner with task management sections, priority lists, and a smart layout for productivity.",
    features: ["Weekly + daily", "Task sections", "Lay-flat binding", "Ribbon bookmark"],
  },

  // ─── Creator Gear ─────────────────────────────────────────────────────────
  {
    id: "21",
    slug: "blue-yeti-x-microphone",
    name: "Blue Yeti X",
    brand: "Blue",
    price: 169,
    category: "creator-gear",
    rating: 4.8,
    reviewCount: 2847,
    image: "https://images.unsplash.com/photo-1598550874175-4d0ef436c909?w=800&q=80",
    hoverImage: "https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=800&q=80",
    isBestseller: true,
    description: "Professional multi-pattern USB microphone with high-res LED metering, perfect for podcasting and streaming.",
    features: ["4 pickup patterns", "24-bit/48kHz", "Real-time monitoring", "Blue VO!CE FX"],
  },
  {
    id: "22",
    slug: "elgato-stream-deck-mk2",
    name: "Elgato Stream Deck MK.2",
    brand: "Elgato",
    price: 149,
    category: "creator-gear",
    rating: 4.8,
    reviewCount: 5621,
    image: "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=800&q=80",
    hoverImage: "https://images.unsplash.com/photo-1598550874175-4d0ef436c909?w=800&q=80",
    isNew: true,
    description: "15 customizable LCD keys to launch apps, switch scenes, control audio, and automate workflows instantly.",
    features: ["15 LCD keys", "Fully customizable", "Plugin ecosystem", "Multi-action keys"],
  },
  {
    id: "23",
    slug: "logitech-mx-master-3s",
    name: "Logitech MX Master 3S",
    brand: "Logitech",
    price: 99,
    category: "creator-gear",
    rating: 4.9,
    reviewCount: 4213,
    image: "https://images.unsplash.com/photo-1527814050087-3793815479db?w=800&q=80",
    hoverImage: "https://images.unsplash.com/photo-1598550874175-4d0ef436c909?w=800&q=80",
    isBestseller: true,
    description: "Ergonomic wireless mouse with 8K DPI precision, silent clicks, and ultra-fast MagSpeed scrolling.",
    features: ["8000 DPI", "Silent clicks", "MagSpeed scroll", "Multi-device"],
  },
  {
    id: "24",
    slug: "sony-zv-e10-camera",
    name: "Sony ZV-E10",
    brand: "Sony",
    price: 699,
    originalPrice: 748,
    category: "creator-gear",
    rating: 4.7,
    reviewCount: 1832,
    image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&q=80",
    hoverImage: "https://images.unsplash.com/photo-1598550874175-4d0ef436c909?w=800&q=80",
    description: "Vlog-optimized APS-C mirrorless camera with interchangeable lenses, perfect for creators and content makers.",
    features: ["24.2MP APS-C", "4K video", "Flip-out screen", "Live streaming"],
  },
  {
    id: "25",
    slug: "harman-kardon-aura-studio",
    name: "Harman Kardon Aura Studio 3",
    brand: "Harman Kardon",
    price: 199,
    category: "creator-gear",
    rating: 4.5,
    reviewCount: 742,
    image: "https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&q=80",
    hoverImage: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&q=80",
    description: "Iconic dome-shaped Bluetooth speaker with 360° sound and ambient lighting. A desk art piece that sounds incredible.",
    features: ["360° audio", "Ambient glow", "Bluetooth 5.0", "30W output"],
  },

  // ─── Lifestyle ────────────────────────────────────────────────────────────
  {
    id: "26",
    slug: "otherland-candle",
    name: "Otherland Signature Candle",
    brand: "Otherland",
    price: 36,
    category: "lifestyle",
    rating: 4.7,
    reviewCount: 894,
    image: "https://images.unsplash.com/photo-1608181831718-c9fdc9a86f14?w=800&q=80",
    hoverImage: "https://images.unsplash.com/photo-1602524816-0a7ca15c5a53?w=800&q=80",
    description: "Hand-poured soy wax candle with complex, refined fragrance profiles designed for contemplative work sessions.",
    features: ["Soy wax blend", "50hr burn time", "Complex scent", "Recyclable glass"],
  },
  {
    id: "27",
    slug: "yield-design-ceramic-mug",
    name: "Yield Design Mug",
    brand: "Yield Design",
    price: 65,
    category: "lifestyle",
    rating: 4.8,
    reviewCount: 312,
    image: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=800&q=80",
    hoverImage: "https://images.unsplash.com/photo-1608181831718-c9fdc9a86f14?w=800&q=80",
    isBestseller: true,
    description: "Handcrafted stoneware mug with a clean, minimal silhouette that feels as good as it looks on your desk.",
    features: ["Handcrafted", "Stoneware clay", "Dishwasher safe", "12oz capacity"],
  },
  {
    id: "28",
    slug: "fellow-stagg-ekg-kettle",
    name: "Fellow Stagg EKG Kettle",
    brand: "Fellow",
    price: 165,
    originalPrice: 195,
    category: "lifestyle",
    rating: 4.9,
    reviewCount: 1543,
    image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&q=80",
    hoverImage: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=800&q=80",
    isNew: true,
    description: "Pour-over kettle with precision temperature control, built-in stopwatch, and stunning minimal aesthetics.",
    features: ["0.9L capacity", "±1°F accuracy", "Built-in timer", "Keep warm mode"],
  },
  {
    id: "29",
    slug: "gantri-table-lamp",
    name: "Gantri Table Light",
    brand: "Gantri",
    price: 245,
    category: "lifestyle",
    rating: 4.6,
    reviewCount: 189,
    image: "https://images.unsplash.com/photo-1513506003901-1e6a35f83338?w=800&q=80",
    hoverImage: "https://images.unsplash.com/photo-1608181831718-c9fdc9a86f14?w=800&q=80",
    description: "3D-printed designer lamp with warm, diffused light. Every piece is made to order in California.",
    features: ["3D printed", "Warm LED", "Touch dimmer", "Made in USA"],
  },
  {
    id: "30",
    slug: "aeropress-coffee-maker",
    name: "AeroPress Go",
    brand: "AeroPress",
    price: 42,
    category: "lifestyle",
    rating: 4.8,
    reviewCount: 3201,
    image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&q=80",
    hoverImage: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=800&q=80",
    description: "Portable total immersion brewer that makes barista-grade coffee anywhere. The desk staple of coffee lovers.",
    features: ["Brews in 1 min", "BPA-free plastic", "Travel mug included", "350+ recipes"],
  },

  // ─── Ergonomics ───────────────────────────────────────────────────────────
  {
    id: "31",
    slug: "grovemade-wrist-rest",
    name: "Grovemade Wrist Rest",
    brand: "Grovemade",
    price: 65,
    category: "ergonomics",
    rating: 4.7,
    reviewCount: 428,
    image: "https://images.unsplash.com/photo-1618384852429-e259b09e6904?w=800&q=80",
    hoverImage: "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=800&q=80",
    description: "Full-grain leather and solid walnut wrist rest that cradles your wrists during long typing sessions.",
    features: ["Full-grain leather", "Walnut wood base", "Non-slip bottom", "Multiple sizes"],
  },
  {
    id: "32",
    slug: "topo-anti-fatigue-mat",
    name: "Topo Anti-Fatigue Mat",
    brand: "Ergodriven",
    price: 99,
    category: "ergonomics",
    rating: 4.6,
    reviewCount: 892,
    image: "https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=800&q=80",
    hoverImage: "https://images.unsplash.com/photo-1592078615290-033ee584e267?w=800&q=80",
    isBestseller: true,
    description: "Topographical standing mat with raised terrain to encourage micro-movements and reduce fatigue.",
    features: ["Topographical design", "High-density foam", "Removable toe bar", "Easy to clean"],
  },
  {
    id: "33",
    slug: "flexispot-e7-standing-desk",
    name: "FlexiSpot E7 Standing Desk",
    brand: "FlexiSpot",
    price: 499,
    originalPrice: 619,
    category: "ergonomics",
    rating: 4.7,
    reviewCount: 2341,
    image: "https://images.unsplash.com/photo-1592078615290-033ee584e267?w=800&q=80",
    hoverImage: "https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=800&q=80",
    isNew: true,
    description: "Height-adjustable electric sit-stand desk with dual motor, 3 memory presets, and 48x30 inch top.",
    features: ["Dual motor", "3 memory presets", "Anti-collision", "320lb capacity"],
  },
  {
    id: "34",
    slug: "oakywood-laptop-stand",
    name: "Oakywood Laptop Stand",
    brand: "Oakywood",
    price: 89,
    category: "ergonomics",
    rating: 4.8,
    reviewCount: 631,
    image: "https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=800&q=80",
    hoverImage: "https://images.unsplash.com/photo-1592078615290-033ee584e267?w=800&q=80",
    description: "Minimalist wooden laptop stand crafted from certified sustainable walnut or maple. Raises screen to eye level.",
    features: ["Certified wood", "Non-slip base", "All laptops fit", "Cable space"],
  },

  // ─── Digital Products ─────────────────────────────────────────────────────
  {
    id: "35",
    slug: "notion-workspace-kit",
    name: "Ultimate Notion Workspace Kit",
    brand: "TRENDY STUDIO",
    price: 29,
    category: "digital",
    rating: 4.9,
    reviewCount: 1204,
    image: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&q=80",
    hoverImage: "https://images.unsplash.com/photo-1557683311-eac922347aa1?w=800&q=80",
    isNew: true,
    isDigital: true,
    description: "Complete Notion workspace system: project management, habit tracker, reading log, goal setting, and more — 12 templates.",
    features: ["12 templates", "Instant download", "Lifetime access", "Free updates"],
  },
  {
    id: "36",
    slug: "creator-starter-bundle",
    name: "Creator Starter Bundle",
    brand: "TRENDY STUDIO",
    price: 49,
    category: "digital",
    rating: 4.8,
    reviewCount: 432,
    image: "https://images.unsplash.com/photo-1557683311-eac922347aa1?w=800&q=80",
    hoverImage: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&q=80",
    isBestseller: true,
    isDigital: true,
    description: "Everything you need to start creating: icon pack, wallpapers, Notion templates, and a workspace setup guide.",
    features: ["500+ icons", "20 wallpapers", "5 Notion templates", "PDF guide"],
  },
  {
    id: "37",
    slug: "premium-icon-pack",
    name: "Premium Icon Pack (600+)",
    brand: "TRENDY STUDIO",
    price: 19,
    category: "digital",
    rating: 4.7,
    reviewCount: 876,
    image: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&q=80",
    hoverImage: "https://images.unsplash.com/photo-1557683311-eac922347aa1?w=800&q=80",
    isDigital: true,
    description: "600+ minimal, consistent icons in SVG and PNG format — designed for apps, Notion, Figma, and beyond.",
    features: ["600+ icons", "SVG + PNG", "Light & dark", "Commercial license"],
  },
  {
    id: "38",
    slug: "deep-work-wallpaper-collection",
    name: "Deep Work Wallpapers",
    brand: "TRENDY STUDIO",
    price: 12,
    category: "digital",
    rating: 4.8,
    reviewCount: 1547,
    image: "https://images.unsplash.com/photo-1557683311-eac922347aa1?w=800&q=80",
    hoverImage: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&q=80",
    isNew: true,
    isDigital: true,
    description: "30 curated minimal wallpapers for Mac, Windows, and mobile. Designed to keep your workspace distraction-free.",
    features: ["30 wallpapers", "4K resolution", "macOS + Windows", "Mobile included"],
  },
];

export const FOOTER_LINKS = {
  Shop: [
    { label: "All Products", href: "/collections" },
    { label: "Keyboards", href: "/collections?category=keyboards" },
    { label: "Workspace Tech", href: "/collections?category=workspace" },
    { label: "Creator Gear", href: "/collections?category=creator-gear" },
    { label: "Productivity", href: "/collections?category=productivity" },
    { label: "Lifestyle", href: "/collections?category=lifestyle" },
    { label: "Digital Downloads", href: "/collections?category=digital" },
    { label: "New Arrivals", href: "/collections?filter=new" },
    { label: "Bestsellers", href: "/collections?filter=bestseller" },
  ],
  Company: [
    { label: "About Us", href: "/about" },
    { label: "Blog", href: "/blog" },
    { label: "Careers", href: "/careers" },
    { label: "Press", href: "/press" },
  ],
  Support: [
    { label: "Contact", href: "/contact" },
    { label: "FAQ", href: "/faq" },
    { label: "Shipping", href: "/shipping" },
    { label: "Returns", href: "/returns" },
    { label: "Warranty", href: "/warranty" },
  ],
};

